/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pd3;

/**
 *
 * @author Frooodooo
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
        this.ButtonCount.setText("Count");
        this.labelmax.setText("Max");
        this.labelmin.setText("Min");
        this.labelreiz.setText("Reizinajums");
        this.labelsk1.setText("1. Skailis");
        this.labelsk2.setText("2. Skailis");
        this.labelstarp.setText("Starpiba");
        this.labelsum.setText("Summa");
        this.labelvid.setText("Videjais");
        this.textmax.setText("0");
        this.textmin.setText("0");
        this.textreiz.setText("0");
        this.textstarp.setText("0");
        this.textsum.setText("0");
        this.textvid.setText("0");
        this.textsk1.setText("0");
        this.textsk2.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelsk1 = new javax.swing.JLabel();
        labelsk2 = new javax.swing.JLabel();
        textsk1 = new javax.swing.JTextField();
        textsk2 = new javax.swing.JTextField();
        ButtonCount = new javax.swing.JButton();
        labelsum = new javax.swing.JLabel();
        labelstarp = new javax.swing.JLabel();
        labelreiz = new javax.swing.JLabel();
        labelmax = new javax.swing.JLabel();
        labelmin = new javax.swing.JLabel();
        labelvid = new javax.swing.JLabel();
        textsum = new javax.swing.JTextField();
        textstarp = new javax.swing.JTextField();
        textreiz = new javax.swing.JTextField();
        textmax = new javax.swing.JTextField();
        textmin = new javax.swing.JTextField();
        textvid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelsk1.setText("jLabel1");

        labelsk2.setText("jLabel2");

        textsk1.setText("jTextField1");

        textsk2.setText("jTextField2");

        ButtonCount.setText("jButton1");
        ButtonCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCountActionPerformed(evt);
            }
        });

        labelsum.setText("jLabel1");

        labelstarp.setText("jLabel2");

        labelreiz.setText("jLabel3");

        labelmax.setText("jLabel4");

        labelmin.setText("jLabel5");

        labelvid.setText("jLabel6");

        textsum.setText("jTextField1");

        textstarp.setText("jTextField2");

        textreiz.setText("jTextField3");

        textmax.setText("jTextField4");

        textmin.setText("jTextField5");

        textvid.setText("jTextField6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelsk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textsk2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelsk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textsk1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelstarp, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelreiz, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelsum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelvid)
                    .addComponent(labelmin)
                    .addComponent(labelmax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textsum, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(textstarp)
                    .addComponent(textreiz)
                    .addComponent(textmax)
                    .addComponent(textmin)
                    .addComponent(textvid))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsk1)
                            .addComponent(textsk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsk2)
                            .addComponent(textsk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textsum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelsum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textstarp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelstarp)
                            .addComponent(ButtonCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textreiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelreiz))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelmax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textvid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelvid))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCountActionPerformed
        String sk1 = this.textsk1.getText();
        String sk2 = this.textsk2.getText();
        int skaitlis1 = Integer.valueOf(sk1);
        int skaitlis2 = Integer.valueOf(sk2);
        
        
        
        this.textsum.setText(String.valueOf(skaitlis1 + skaitlis2));
        this.textstarp.setText(String.valueOf(skaitlis1 - skaitlis2));
        this.textreiz.setText(String.valueOf(skaitlis1 * skaitlis2));
        this.textmax.setText(String.valueOf(Math.max(skaitlis1, skaitlis2)));
        this.textmin.setText(String.valueOf(Math.min(skaitlis1, skaitlis2)));
        this.textvid.setText(String.valueOf((skaitlis1 + skaitlis2) / 2 ));
    }//GEN-LAST:event_ButtonCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelmax;
    private javax.swing.JLabel labelmin;
    private javax.swing.JLabel labelreiz;
    private javax.swing.JLabel labelsk1;
    private javax.swing.JLabel labelsk2;
    private javax.swing.JLabel labelstarp;
    private javax.swing.JLabel labelsum;
    private javax.swing.JLabel labelvid;
    private javax.swing.JTextField textmax;
    private javax.swing.JTextField textmin;
    private javax.swing.JTextField textreiz;
    private javax.swing.JTextField textsk1;
    private javax.swing.JTextField textsk2;
    private javax.swing.JTextField textstarp;
    private javax.swing.JTextField textsum;
    private javax.swing.JTextField textvid;
    // End of variables declaration//GEN-END:variables
}
