/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack;

import Graphic.*;
import data.*;

/**
 *
 * @author Frooodooo
 */
public class MainForm extends javax.swing.JFrame {

    private Table table;
    private CardHolder dealerCards;
    private CardHolder playerCards;
    
    public MainForm() {
        initComponents();
        
        
        this.labelinfo.setText("pazinojums");
        this.buttonvel.setText("Vel karti");
        this.buttonpietiek.setText("Pietiek");
        this.buttonretry.setText("Spelet Velreiz");
    table = new Table();
    dealerCards = new CardHolder();
    playerCards = new CardHolder();
    
    this.dilerapanel.add(dealerCards);
    this.playerpanel.add(playerCards);
    
    startNewGame();
    
    }
    private void refreshCards(boolean showDealerCards)
    {
       //notiris esosas kartis
        dealerCards.clear();
        playerCards.clear();
        //attelo speletaja kartis
        table.getPlayerCards().forEach((c) -> {
            playerCards.addCard(new CardImage(c, false));
        });
        //attelo dilera kartis
        table.getDealerCards().forEach((c) -> {
            dealerCards.addCard(new CardImage(c, 
            !showDealerCards));
        });
        this.labelspeletajs.setText("Punkti: " + table.getPlayerPoints());
        if(showDealerCards)
        {
        this.labeldileris.setText("Punkti: " + table.getDealerPoints());
        this.labeldileris.setVisible(true);
        }
    }
    private void startNewGame()
    {
        this.buttonvel.setVisible(true);
        this.buttonpietiek.setVisible(true);
        this.buttonretry.setVisible(false);
        this.labeldileris.setVisible(false);
        this.labelinfo.setVisible(false);
        table.startNewGame();
        refreshCards(false);
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dilerapanel = new javax.swing.JPanel();
        playerpanel = new javax.swing.JPanel();
        labeldileris = new javax.swing.JLabel();
        labelspeletajs = new javax.swing.JLabel();
        buttonretry = new javax.swing.JButton();
        buttonpietiek = new javax.swing.JButton();
        buttonvel = new javax.swing.JButton();
        labelinfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dilerapanel.setBackground(new java.awt.Color(100, 120, 40));

        playerpanel.setBackground(new java.awt.Color(100, 120, 40));

        labeldileris.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeldileris.setText("jLabel1");

        labelspeletajs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelspeletajs.setText("jLabel2");

        buttonretry.setText("jButton1");
        buttonretry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonretryActionPerformed(evt);
            }
        });

        buttonpietiek.setText("jButton2");
        buttonpietiek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpietiekActionPerformed(evt);
            }
        });

        buttonvel.setText("jButton2");
        buttonvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvelActionPerformed(evt);
            }
        });

        labelinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelinfo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeldileris, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dilerapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelspeletajs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonpietiek)
                        .addGap(12, 12, 12)
                        .addComponent(buttonvel)
                        .addGap(37, 37, 37))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(buttonretry, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(labelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dilerapanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labeldileris, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonpietiek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonvel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonretry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelspeletajs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))))
                .addComponent(playerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvelActionPerformed
        table.givePlaverCard();
        refreshCards(false);
    }//GEN-LAST:event_buttonvelActionPerformed

    private void buttonretryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonretryActionPerformed
        startNewGame();
    }//GEN-LAST:event_buttonretryActionPerformed

    private void buttonpietiekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpietiekActionPerformed
        this.buttonretry.setVisible(true);
        table.dealerTurn();
        refreshCards(true);
        
        String result = table.getResult();
        this.labelinfo.setText(result);
        this.labelinfo.setVisible(true);
        this.buttonvel.setVisible(false);
        this.buttonpietiek.setVisible(false);
        
    }//GEN-LAST:event_buttonpietiekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonpietiek;
    private javax.swing.JButton buttonretry;
    private javax.swing.JButton buttonvel;
    private javax.swing.JPanel dilerapanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeldileris;
    private javax.swing.JLabel labelinfo;
    private javax.swing.JLabel labelspeletajs;
    private javax.swing.JPanel playerpanel;
    // End of variables declaration//GEN-END:variables
}
   
